export default class JotformPowershopLabs {
  constructor(el) {
    this.el = el

	JotForm.init(function(){ setTimeout(function() { $('input_7').hint('ex: myname@example.com'); }, 20); JotForm.clearFieldOnHide="disable"; /*INIT-END*/
	}); JotForm.prepareCalculationsOnTheFly([null,{"name":"heading","qid":"1","text":"Powershop Labs","type":"control_head"},{"name":"submit","qid":"2","text":"Submit","type":"control_button"},{"name":"fullName","qid":"3","text":"Full Name","type":"control_textbox"},null,{"name":"phone","qid":"5","text":"Phone","type":"control_textbox"},null,{"name":"email7","qid":"7","text":"E-mail","type":"control_email"},{"name":"whatAspects","qid":"8","text":"What aspects of your idea are you looking for assistance with?","type":"control_dropdown"},{"name":"location","qid":"9","text":"Location","type":"control_textbox"},{"name":"companyName","qid":"10","text":"Company name (if applicable)","type":"control_textbox"},{"name":"australianBusiness","qid":"11","text":"Australian Business Number (if applicable)","type":"control_textbox"},{"name":"whatYear","qid":"12","text":"What year did you establish your start-up?","type":"control_textbox"},{"name":"describeYour","qid":"13","text":"Describe your idea in more detail","type":"control_textarea"},{"name":"termsAnd","qid":"14","text":"Terms and conditions","type":"control_checkbox"}]); setTimeout(function() {
	JotForm.paymentExtrasOnTheFly([null,{"name":"heading","qid":"1","text":"Powershop Labs","type":"control_head"},{"name":"submit","qid":"2","text":"Submit","type":"control_button"},{"name":"fullName","qid":"3","text":"Full Name","type":"control_textbox"},null,{"name":"phone","qid":"5","text":"Phone","type":"control_textbox"},null,{"name":"email7","qid":"7","text":"E-mail","type":"control_email"},{"name":"whatAspects","qid":"8","text":"What aspects of your idea are you looking for assistance with?","type":"control_dropdown"},{"name":"location","qid":"9","text":"Location","type":"control_textbox"},{"name":"companyName","qid":"10","text":"Company name (if applicable)","type":"control_textbox"},{"name":"australianBusiness","qid":"11","text":"Australian Business Number (if applicable)","type":"control_textbox"},{"name":"whatYear","qid":"12","text":"What year did you establish your start-up?","type":"control_textbox"},{"name":"describeYour","qid":"13","text":"Describe your idea in more detail","type":"control_textarea"},{"name":"termsAnd","qid":"14","text":"Terms and conditions","type":"control_checkbox"}]);}, 20);
  }
}

